-- ============================================================================
-- 065 — Nine activities the library was missing
-- ============================================================================
--
-- Phase 2A.5 asked for a previously-researched candidate list to be evaluated
-- editorially, and only the genuinely missing ones added. Six were dropped on
-- inspection because the library already answers them:
--
--   Contact Point Drill  -> "Tee Work — Ball Out In Front" IS the contact point
--                           drill; the tee is moved in front of the plate for
--                           exactly this reason.
--   Short Bat Drill      -> near-identical to "Mini Wiffle Ball & Skinny Bat",
--                           which constrains the barrel the same way. A second
--                           row would be a duplicate under a different name.
--   Bottle Cap Drill     -> the same drill again with a smaller object. A
--                           variation of the skinny-bat row at most, and one
--                           nobody has asked for.
--   Pitcher's Count      -> overlaps "Two-Strike Hitting Adjustment Drill"; the
--                           counts differ, the adjustment does not.
--   Throwing Footwork
--     Progression        -> overlaps the crow hop rows.
--   Crow Hop Corners     -> the brief itself said "if materially distinct", and
--                           nothing available shows that it is.
--
-- Adding any of those would have made the duplicate problem worse in the same
-- week it was fixed.
--
-- The nine below are real gaps, checked by name and by concept against all 211
-- rows. Four are baserunning, which is the thinnest and most neglected part of
-- this library: it holds thirteen rows, five taxonomy problems, and until now
-- nothing at all on tagging up, reading a ball in the dirt, deciding whether to
-- round first, or attaching a sprint to a swing.
--
-- Written for BenchCoach. No source text is copied, no video is claimed, and
-- every calibration figure is one the drill's own description supports.
--
-- Idempotent: fixed UUIDs, ON CONFLICT DO NOTHING.
-- ============================================================================

INSERT INTO public.drill_resources (
  id, drill_name, skill_category, primary_skill, secondary_skill,
  description, ai_coaching_notes, safety_notes, success_markers,
  reps_guidance, regression_notes, progression_notes,
  mechanic_focus, common_flaws_fixed, tags,
  age_range, min_age, max_age, difficulty_level, progression_level,
  competition_level, equipment_needed, indoor_outdoor, space_required,
  requires_partner, est_duration_minutes, activity_format, practice_roles,
  min_players, max_players, ideal_group_size, min_coaches, station_friendly,
  rep_density, idle_time_risk, engagement_level, competition_style,
  instruction_complexity, throwing_load, physical_intensity,
  mixed_skill_friendly, resource_kind, status, source, created_by_coach_id
) VALUES
('2a82682f-f56c-527b-ba67-b57bd5a62e4d','Stride Box','Hitting','stride control','balance','Two lines on the ground — chalk, tape, or a pair of bats laid down — marking where the front foot starts and where it should land. The hitter takes normal swings off a tee or front toss and the only rule is that the front foot lands inside the box. A stride that drifts open, closes off, or grows by six inches when the hitter tries to do more is invisible to them and obvious the moment there is a line to miss.','Cue "same foot, same spot, every swing". Watch the BACK foot as well: a hitter who cannot keep the stride in the box usually has the back side collapsing first, and fixing the front foot alone will not hold. A front foot landing outside the box toward the plate is diving; outside away from it is bailing. Same miss, two different problems.',NULL,ARRAY['Front foot lands inside the box on eight of ten swings','The tenth stride looks like the first','The hitter notices a miss before the coach mentions it'],'2 rounds of 10 swings','Drop to one line, for the landing spot only, and let the hitter stride to it at their own pace with no ball involved.','Move from tee to front toss, then have the feeder vary the timing — a late toss is what makes a stride grow.',ARRAY['stride direction','stride length','balance through the swing'],ARRAY['stepping in the bucket','diving at the ball','inconsistent stride','loses posture'],ARRAY['hitting','stride','constraint','tee','beginner'],'8-14',8,14,'Beginner',2,'both',ARRAY['chalk, tape or two spare bats','tee','baseballs','bat'],'Both','Small',false,10,'station',ARRAY['teach','isolate','repetition'],1,NULL,4,0,true,'high','low','medium','none','low','none','low',true,'activity','approved','benchcoach_original',NULL),
('9847fa60-e5cd-53af-9831-5c6424dfe80c','Drop Ball Drill','Hitting','bat path','hand speed','The feeder stands beside the hitter and slightly in front, holds a ball at about shoulder height on an outstretched arm, and simply lets go. The hitter has to get the barrel there before it lands. No toss, no arc, nothing to read but the release. It is the shortest possible gap between now and swing, which is why it finds a long or slow path faster than any tee can.','Cue "short to it". The failure is almost never reaction time — it is path length, and a hitter who keeps missing is going around the ball rather than to it. When they need more time, drop from LOWER. Dropping closer to the hitter gives them no more time and puts the feeder''s hand in the swing.','The feeder''s hand and forearm are near the swing path. Stand beside and slightly in front of the hitter, never in front of the plate, release and withdraw in one motion, and keep a helmet on the hitter. Start slow enough that the feeder is never guessing when the swing is coming.',ARRAY['Barrel meets the ball above knee height','Contact happens out front, not beside the back foot','Six clean of ten'],'2 rounds of 10 drops','Drop from waist height so the ball has further to fall and the hitter has longer to find it.','Drop from higher, then hold two balls and release one — the hitter reads which.',ARRAY['bat path','hand speed','contact point'],ARRAY['long swing','casting','slow hands','late contact'],ARRAY['hitting','reaction','hand-eye','feeder','intermediate'],'9-14',9,14,'Intermediate',3,'both',ARRAY['baseballs or soft-core balls','batting helmet','bat'],'Both','Small',true,8,'partner',ARRAY['isolate','repetition'],2,NULL,3,0,true,'high','low','high','none','low','none','low',false,'activity','approved','benchcoach_original',NULL),
('2f3326af-9848-534e-9cc2-3d0f628c1162','Recovery Drill','Fielding (Infield)','recovery after a misplay','barehand pick','The coach deliberately rolls balls that cannot be fielded cleanly — off to the side, off the heel of the glove, a short hop that eats the fielder up. The rep does not end at the bobble. The fielder finds the ball, picks it barehanded if that is quicker, and still makes the throw. Youth infielders practise clean ground balls almost exclusively and then meet their first bad hop in a game, where the ball on the ground is not the error. Standing and looking at it is.','Cue "find it, then go". The clock a fielder imagines after a bobble is always shorter than the real one — on most youth fields there is still time to get the out, and believing that is most of the drill. Watch for the head dropping and the shoulders following it: a player who has already got annoyed has stopped playing, and that is the habit worth interrupting rather than the bobble.',NULL,ARRAY['Moves to the loose ball rather than reaching for it','Barehands it when the ball has stopped','Completes the throw on more than half the bad reps'],'10 deliberately bad balls per player','Roll only slightly off-line so the ball can still be fielded, and ask for a clean pick-up with no throw at all.','Add a runner, or a stopwatch, so the throw has to beat something real.',ARRAY['recovery after a misplay','barehand pick','throwing under time pressure'],ARRAY['gives up after a bobble','rushes the throw after a mistake','poor footwork'],ARRAY['infield','mistakes','resilience','game situation'],'9-14',9,14,'Intermediate',3,'both',ARRAY['glove','baseballs'],'Both','Medium',false,10,'station',ARRAY['repetition','decision','game_application'],1,NULL,4,1,true,'medium','medium','high','none','medium','medium','medium',true,'activity','approved','benchcoach_original',NULL),
('f3ca0dde-8e0c-56f3-8791-29c0e51045f2','Grounder to First, Pitcher Covers','Team Defense','pitcher covering first','feed timing','A ground ball to the right side pulls the first baseman off the bag and somebody has to be there. The coach hits or rolls to first, the first baseman fields it, and the pitcher breaks for the bag on contact — every time, including the times the first baseman stays home and takes it themselves. The feed is a soft underhand toss led in front of the pitcher, chest high, to a spot they are running to.','Cue "break on contact, not on the bobble". The standard youth version is the pitcher watching the play develop and arriving late, and the fix is making the break automatic rather than conditional. The feed goes where the pitcher WILL be: a toss aimed at where they are is behind them by the time it arrives. Catch first, then find the bag — a pitcher hunting for the base with the ball still in the air misses both.','The pitcher and the runner arrive at the same base from different directions. Run the bag on the foul side and past it, and do not add a live runner until the footwork is automatic.',ARRAY['Pitcher moves on contact without being told','Catches the feed before touching the bag','Runs through toward the infield rather than stopping on the bag'],'8-10 reps with the pitcher rotating','Walk it through with no ball, then at half speed, so the path and the timing are learned before the catch is added.','Mix in balls the first baseman can take unassisted, so the pitcher breaks every time and gets waved off some of them.',ARRAY['pitcher covering first','feed timing','footwork at the bag'],ARRAY['pitcher does not cover','late break','collision at first base'],ARRAY['team defense','pitchers','first base','game situation'],'9-14',9,14,'Intermediate',3,'both',ARRAY['gloves','baseballs','bases'],'Outdoor','Medium',false,12,'full_team',ARRAY['team_execution','game_application'],3,NULL,6,1,false,'medium','medium','medium','none','medium','medium','medium',true,'activity','approved','benchcoach_original',NULL),
('07a59bb9-1b7c-554a-a1f1-98f4af671e21','On the Run','Fielding (Fly Balls)','catching on the move','route running','The coach starts the outfielder moving before the ball is in the air — a jog left, right, or straight in — and then throws or hits a ball that has to be caught while they are still moving. Nothing is hit to where the player is standing. Almost all youth outfield practice is a ball sent to a stationary player, and almost no ball in a game arrives that way.','Cue "run first, glove last". A glove that comes up on the first step slows the player down and costs more ground than it saves. Watch the route rather than the catch: a player drifting in a curve is reading late, and the thing to fix is the first step, not the speed.',NULL,ARRAY['Glove comes up in the last two strides, not the first','Runs a straight line to the spot','Two hands when there is time, one when there is not'],'8-10 per player, alternating directions','Start the player moving and throw the ball to where they already are, so the movement is the only new thing.','Stop calling the direction and let them read it off the coach''s swing.',ARRAY['route running','catching on the move','first step'],ARRAY['drifts to the ball','glove up too early','poor routes','slow first step'],ARRAY['outfield','fly balls','movement','intermediate'],'9-14',9,14,'Intermediate',3,'both',ARRAY['glove','baseballs'],'Outdoor','Full field',false,10,'station',ARRAY['repetition','progress'],1,NULL,4,1,true,'medium','medium','high','none','low','none','high',true,'activity','approved','benchcoach_original',NULL),
('d358d3cd-7da8-5baf-9843-3fe2a81a6773','Swing and Sprint','Baserunning','out of the box','running through first','A full swing off a tee or front toss, and then the hitter runs — properly, all the way through the base, every single time. No jogging, no watching the ball, no eighty percent. The bat is placed down rather than thrown. Youth players take hundreds of swings a week and attach running to almost none of them, so in a game the first three steps out of the box are the steps they have never practised.','Cue "drop it and go". The tell is a hitter who watches the ball before moving: on a youth field a batted ball is nearly always still in play, and that half-second is the whole difference between safe and out. Run THROUGH the base rather than to it — a player who slows down two steps early has turned a close play into an out without knowing it.','The bat goes down in a designated spot, never thrown. Nobody stands on the first-base line while a hitter is running.',ARRAY['First step is toward first, not back toward the plate','Bat placed down, clear of the path','Runs past the bag without slowing'],'10 swings, each with a full run','Split it — swing, freeze, then run on a whistle — so the two halves join at the player''s own pace.','The coach calls "fair" or "foul" as the ball leaves, and the runner reacts to it.',ARRAY['out of the box','running through first','swing to sprint transition'],ARRAY['watches the ball','slow out of the box','throws the bat','stops at the bag'],ARRAY['baserunning','hitting','conditioning','game situation'],'7-13',7,13,'Beginner',2,'both',ARRAY['bat','tee or baseballs','batting helmet','bases'],'Outdoor','Medium',false,10,'small_group',ARRAY['repetition','game_application','finish'],1,NULL,6,1,true,'medium','medium','high','none','low','none','high',true,'activity','approved','benchcoach_original',NULL),
('92366675-97a6-5d04-b3b6-5a2909ce858f','First Base Decision','Baserunning','reading the ball out of the box','rounding technique','The runner starts in the box and the coach points — or rolls a ball — to the infield or the outfield just after the imaginary swing. Ball on the ground in the infield: run through the bag. Ball through to the outfield: round it hard and look. Same start, two answers, and the runner has to pick one while already moving. Most young runners have exactly one setting, and it is usually the wrong one for whichever ball just happened.','Cue "through it or around it — decide before the bag, not on it". A runner who rounds everything gives away outs at first; one who runs through everything gives away second on a ball in the gap. Watch the path: a proper round starts with a small arc three steps BEFORE the bag, not a hard left turn on top of it.',NULL,ARRAY['Arcs out early on a ball to the outfield','Runs straight through on an infield ground ball','Looks at the ball rather than at the coach'],'10 decisions, mixed','Announce the answer before the start, so the running is practised before the deciding is added.','A live fungo instead of a pointed direction, so the read comes off a real ball.',ARRAY['reading the ball out of the box','rounding technique','running through the bag'],ARRAY['rounds everything','runs through everything','watches the coach instead of the ball'],ARRAY['baserunning','decisions','game IQ','first base'],'8-13',8,13,'Beginner',2,'both',ARRAY['bases','baseballs','batting helmet'],'Outdoor','Medium',false,10,'small_group',ARRAY['decision','game_application'],1,NULL,6,1,true,'medium','medium','medium','none','medium','none','medium',true,'activity','approved','benchcoach_original',NULL),
('3e15ab9d-f443-5a82-87df-8c4cc418c2e6','Progressive Tag Up','Baserunning','tagging up','reading a ball in the air','A runner on a base, a coach with a ball, and a fielder to catch it. The coach throws a fly ball; the runner goes back to the base, watches the catch, and leaves on the catch — not before it, not a beat after. Three rounds: first the runner is told to tag, then told only that a ball is in the air, then given a mix of fly balls, line drives and ground balls so that tagging becomes a decision rather than an instruction.','Cue "leave on the catch, not on the throw". The universal youth error is watching the fielder''s arm instead of their glove; move the runner''s eyes to the catch itself and the timing fixes itself. On a line drive the right answer is to freeze, and the third round is the only place that ever gets practised.',NULL,ARRAY['Foot stays on the base until the ball is caught','Leaves within a stride of the catch','Freezes on a line drive without being told'],'3 rounds of 5','Stand beside the runner and say "now" at the moment of the catch, until the timing is felt rather than counted.','Add a second runner so they have to communicate, and a throw so the tag has to beat something.',ARRAY['tagging up','reading a ball in the air','leaving on the catch'],ARRAY['leaves early','leaves late','runs on a line drive','watches the fielder instead of the ball'],ARRAY['baserunning','tag up','game IQ','fly balls'],'8-14',8,14,'Intermediate',3,'both',ARRAY['bases','baseballs','gloves','batting helmet'],'Outdoor','Medium',false,10,'small_group',ARRAY['decision','team_execution','game_application'],2,NULL,6,1,true,'medium','medium','medium','none','medium','low','medium',true,'activity','approved','benchcoach_original',NULL),
('3f65e53c-eebc-511c-89a9-23e519dffba0','Wild Pitch Advance','Baserunning','reading a ball in the dirt','secondary lead','A runner on base, a catcher or a coach behind the plate, and a ball thrown deliberately into the dirt. The runner reads whether it got past the catcher and goes or stays on that read alone. Some of them are blocked and stay in front, and those are the ones worth practising — the runner who goes on every ball in the dirt is out by fifteen feet, and the one who never goes never takes the base.','Cue "read the ball, not the catcher". A ball that stays in front of the catcher is not a wild pitch, and a runner watching the catcher''s body instead of the ball cannot tell the difference. Secondary lead first: a runner still standing on the bag when the ball hits the dirt has already lost the base, whatever they do next.',NULL,ARRAY['Takes a secondary lead on every pitch','Goes only when the ball actually gets past','Commits fully once committed'],'10 pitches, roughly half of them blocked','The coach calls "go" or "stay" as the ball lands, so the running is practised before the reading is added.','A real catcher blocking at game speed, and a throw down, so the read has to be right AND early.',ARRAY['reading a ball in the dirt','secondary lead','first step'],ARRAY['never advances on a wild pitch','goes on every ball in the dirt','no secondary lead'],ARRAY['baserunning','game IQ','catchers','decisions'],'9-14',9,14,'Intermediate',3,'both',ARRAY['bases','baseballs','catcher''s gear','batting helmet'],'Outdoor','Medium',false,10,'small_group',ARRAY['decision','game_application'],2,NULL,5,1,true,'medium','medium','medium','none','medium','low','medium',true,'activity','approved','benchcoach_original',NULL)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Taxonomy mappings.
--
-- An unmapped drill is reachable only by text search, which is the weakest
-- retrieval path this library has — the standing audit counts those as nearly
-- invisible. Each of these answers a problem that already exists, and several
-- land on the thinnest ones: loses-posture was down to a single drill,
-- base-awareness and bad-base-turns to two.
-- ---------------------------------------------------------------------------
INSERT INTO public.drill_problem_map (drill_id, problem_slug, sort_order, curated) VALUES
  ('2a82682f-f56c-527b-ba67-b57bd5a62e4d','stepping-in-bucket',2,true),
  ('2a82682f-f56c-527b-ba67-b57bd5a62e4d','lunging',2,true),
  ('2a82682f-f56c-527b-ba67-b57bd5a62e4d','loses-posture',2,true),
  ('9847fa60-e5cd-53af-9831-5c6424dfe80c','casting',2,true),
  ('9847fa60-e5cd-53af-9831-5c6424dfe80c','late-timing',2,true),
  ('9847fa60-e5cd-53af-9831-5c6424dfe80c','inconsistent-contact',2,true),
  ('2f3326af-9848-534e-9cc2-3d0f628c1162','poor-fielding-footwork',2,true),
  ('2f3326af-9848-534e-9cc2-3d0f628c1162','slow-transfer',2,true),
  ('f3ca0dde-8e0c-56f3-8791-29c0e51045f2','first-base-footwork',2,true),
  ('07a59bb9-1b7c-554a-a1f1-98f4af671e21','backpedaling-flyballs',2,true),
  ('d358d3cd-7da8-5baf-9843-3fe2a81a6773','slow-first-step',2,true),
  ('d358d3cd-7da8-5baf-9843-3fe2a81a6773','base-awareness',2,true),
  ('92366675-97a6-5d04-b3b6-5a2909ce858f','bad-base-turns',1,true),
  ('92366675-97a6-5d04-b3b6-5a2909ce858f','base-awareness',3,true),
  ('3e15ab9d-f443-5a82-87df-8c4cc418c2e6','base-awareness',4,true),
  ('3f65e53c-eebc-511c-89a9-23e519dffba0','base-awareness',5,true),
  ('3f65e53c-eebc-511c-89a9-23e519dffba0','base-stealing',3,true)
ON CONFLICT DO NOTHING;
