-- ============================================================================
-- 066 — Collection videos, attached to the drills they actually demonstrate
-- ============================================================================
--
-- NOT APPLIED IN THE SESSION THAT WROTE IT. Apply deliberately.
--
-- docs/audits/drill-collection-extraction.csv found 27 cases where a demoted
-- source collection demonstrates an activity the library already holds as its
-- own canonical row. Fourteen of those videos were already attached to the
-- right drill; these are the remaining thirteen.
--
-- The collection rows stay demoted. They are still not drills. What changes is
-- that the video behind them stops being stranded on a row no coach can be
-- offered, and becomes a second piece of media on a row they can.
--
-- WHY THESE CARRY NO TIMESTAMP
--
-- Because none was available. Phase 2B probed for chapter markers, uploader
-- description timestamps and captions across all 118 videos and reached none of
-- them: youtube.com answers 403 to CONNECT under this environment's network
-- policy, recorded per row in docs/audits/drill-media-segment-audit.csv.
--
-- start_seconds is therefore NULL rather than 0, is_primary is FALSE so the
-- drill's own demonstration keeps the top slot, and verification_status is
-- 'unverified'. When evidence arrives, these are the rows the segment lands on
-- — which is most of the point of writing them now.
--
-- Additive. No drill row is modified, nothing is deleted, and ON CONFLICT DO
-- NOTHING against the unique attachment index makes a second run a no-op.
--
-- Generated by scripts/emit-collection-media.ts. Regenerate rather than edit.
-- ============================================================================

-- Collection videos attached to the canonical drills they demonstrate.
-- is_primary false, unverified, start_seconds NULL. No drill row is modified.
insert into drill_media_resources
  (drill_id, media_type, provider, external_id, url, title, source_name,
   thumbnail_url, start_seconds, end_seconds, start_source, is_primary,
   verification_status, notes)
values
('808e703f-d60e-4a0b-8cbd-845bcb4cc1bb'::uuid,'youtube','youtube','Tjzv5anKEe0','https://www.youtube.com/watch?v=Tjzv5anKEe0','Top 5 Blocking Drills for Catchers',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Rapid Fire". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('e7bd95b6-d491-49e2-a383-7fc381e7b0ce'::uuid,'youtube','youtube','y4Ep5hji9TI','https://www.youtube.com/watch?v=y4Ep5hji9TI','Catcher Footwork Skills and Drills',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Receiving stance". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('367642e8-dfd4-4988-90e5-f2c4d10b3401'::uuid,'youtube','youtube','y4Ep5hji9TI','https://www.youtube.com/watch?v=y4Ep5hji9TI','Catcher Footwork Skills and Drills',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Pop-up footwork to second". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('744a47da-ef0c-42b0-b961-1175aaad42d9'::uuid,'youtube','youtube','ZMuVnmUY2CI','https://www.youtube.com/watch?v=ZMuVnmUY2CI','3 Great Outfield Drills for Youth Players',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Drop step mechanics". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('73f5fef2-af64-4577-998d-da854cebb0cf'::uuid,'youtube','youtube','WUIM8NqNETg','https://www.youtube.com/watch?v=WUIM8NqNETg','Essential Outfield Drills — Fly Balls and Ground Balls',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Crow hop mechanics". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('daea5efc-42ce-4a83-9f07-a867dd6fbddd'::uuid,'youtube','youtube','WUIM8NqNETg','https://www.youtube.com/watch?v=WUIM8NqNETg','Essential Outfield Drills — Fly Balls and Ground Balls',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Outfield ground ball technique". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('4c68b693-a617-4827-a732-653c2a64a27d'::uuid,'youtube','youtube','EZtJ9JNPE2k','https://www.youtube.com/watch?v=EZtJ9JNPE2k','3 Simple Fielding Drills for Youth Players',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Proper fielding stance / getting low". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('6a2c9dc7-f08c-47fd-9a08-f9e117f466cb'::uuid,'youtube','youtube','gOE484Meo_o','https://www.youtube.com/watch?v=gOE484Meo_o','10 Best Baseball Hitting Drills for Kids',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Tee work". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('fe94a671-1d24-40fe-9771-4c7f5f708c14'::uuid,'youtube','youtube','gOE484Meo_o','https://www.youtube.com/watch?v=gOE484Meo_o','10 Best Baseball Hitting Drills for Kids',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Soft toss variations". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('a54d536f-e4f0-4dd5-91d2-d007bd274250'::uuid,'youtube','youtube','McHb2hXrTrE','https://www.youtube.com/watch?v=McHb2hXrTrE','Must-Do Youth Pitching Drills for Beginners',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Balance Point Drill". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('4106c25c-beeb-4d11-b1aa-eb9aa85978ae'::uuid,'youtube','youtube','k7OgmDDosck','https://www.youtube.com/watch?v=k7OgmDDosck','Skills and Drills for Baserunning',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Leads". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('f9d5d796-ce11-4964-bc70-a3ce5f8a607f'::uuid,'youtube','youtube','k7OgmDDosck','https://www.youtube.com/watch?v=k7OgmDDosck','Skills and Drills for Baserunning',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Reading pitchers". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.'),
('b610bf25-fbc7-46e3-9c8a-16e07224bf70'::uuid,'youtube','youtube','k7OgmDDosck','https://www.youtube.com/watch?v=k7OgmDDosck','Skills and Drills for Baserunning',NULL,NULL,NULL,NULL,NULL,false,'unverified','Collection video that also demonstrates this drill, as "Sliding". Attached by Phase 2B from the collection extraction audit. No segment: no timestamp evidence was reachable.')
on conflict do nothing;
