-- ============================================================================
-- EXPORT THE PRODUCTION SCHEMA — for people without a terminal
-- ============================================================================
--
-- Paste this whole file into the Supabase SQL editor and run it. It returns
-- the schema of the `public` schema as a list of SQL lines. Download the
-- result as CSV and hand that file back; it becomes migrations/000_baseline.sql.
--
-- THIS IS READ-ONLY. Every statement below is a SELECT against the system
-- catalogs. It creates nothing, changes nothing, and drops nothing. It also
-- reads NO application rows — only the catalog descriptions of tables,
-- columns, constraints, indexes, views, functions, triggers, RLS policies and
-- grants. No coach, player or team data is touched.
--
-- WHY THIS EXISTS
--
-- The usual way to capture a baseline is `pg_dump --schema-only`, which needs
-- a Postgres connection on port 5432. That means a laptop with the client
-- installed. This project is run entirely through the Supabase, Vercel and
-- GitHub web UIs, and every migration is applied by pasting into this same SQL
-- editor — so the capture should work the same way.
--
-- WHAT IT DOES NOT CAPTURE, AND WHY THAT IS FINE
--
--   - anything outside the `public` schema (auth, storage, realtime, vault).
--     A new Supabase project supplies those itself.
--   - object ownership. It differs per project and is not reproducible.
--   - row data. Deliberately.
--
-- The `bwc_*` tables ARE included in the output. They belong to a different
-- application and get stripped during review rather than here, so that the
-- export stays a faithful record of what production contains and the decision
-- to exclude them stays visible in the diff.
-- ============================================================================

WITH
-- Only real, ordinary tables and views in public. Excludes TOAST tables,
-- indexes-as-relations, and anything an extension owns.
rel AS (
  SELECT c.oid, c.relname, c.relkind, c.relrowsecurity
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relkind IN ('r', 'v', 'm', 'p')
    AND NOT EXISTS (
      SELECT 1 FROM pg_depend d
      WHERE d.objid = c.oid AND d.deptype = 'e'   -- owned by an extension
    )
),

-- 0. Preamble --------------------------------------------------------------
-- check_function_bodies = false is not a shortcut, it is required.
--
-- Functions are emitted in name order, and a SQL-language function's body IS
-- validated at CREATE time — so bc_league_at_least, which calls
-- bc_league_role, fails because 'a' sorts before 'r'. Ordering functions by
-- dependency means resolving a graph in a catalog query; pg_dump solves the
-- same problem the same way, by turning body validation off for the load.
-- Every function is still checked the first time it runs.
pre AS (
  SELECT * FROM (VALUES
    (50, '1', '', '-- BenchCoach schema baseline, exported from the Supabase SQL editor.'),
    (50, '2', '', '-- Generated by migrations/EXPORT_SCHEMA.sql. Read-only; contains no row data.'),
    (50, '3', '', 'SET check_function_bodies = false;'),
    (50, '4', '', 'SET search_path = public;')
  ) AS t(sect, ord1, ord2, line)
),

-- 1. Extensions ------------------------------------------------------------
ext AS (
  SELECT 100 AS sect, e.extname AS ord1, '' AS ord2,
         'CREATE EXTENSION IF NOT EXISTS ' || quote_ident(e.extname) ||
         ' WITH SCHEMA ' || quote_ident(n.nspname) || ';' AS line
  FROM pg_extension e
  JOIN pg_namespace n ON n.oid = e.extnamespace
  WHERE e.extname <> 'plpgsql'
),

-- 2. Tables ----------------------------------------------------------------
-- Built column by column rather than with a dump helper, because Postgres has
-- no pg_get_tabledef(). Defaults and NOT NULL come across; constraints are
-- emitted separately below so a circular foreign key cannot make the file
-- unorderable.
tbl AS (
  SELECT 200 AS sect, r.relname AS ord1, '' AS ord2,
         'CREATE TABLE IF NOT EXISTS public.' || quote_ident(r.relname) || ' (' || E'\n' ||
         string_agg(
           '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
           || CASE WHEN a.attidentity <> '' THEN ' GENERATED ' ||
                CASE a.attidentity WHEN 'a' THEN 'ALWAYS' ELSE 'BY DEFAULT' END ||
                ' AS IDENTITY'
              WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
              ELSE '' END
           || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
           ',' || E'\n' ORDER BY a.attnum
         ) || E'\n);' AS line
  FROM rel r
  JOIN pg_attribute a ON a.attrelid = r.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad ON ad.adrelid = r.oid AND ad.adnum = a.attnum
  WHERE r.relkind IN ('r', 'p')
  GROUP BY r.relname
),

-- 3. Constraints -----------------------------------------------------------
-- Primary keys first, then unique and check, then foreign keys last so every
-- table a key references already exists.
cons AS (
  SELECT 300 AS sect,
         CASE con.contype WHEN 'p' THEN '1' WHEN 'u' THEN '2' WHEN 'c' THEN '3' ELSE '4' END
           AS ord1,
         r.relname || con.conname AS ord2,
         'ALTER TABLE public.' || quote_ident(r.relname) ||
         ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' ||
         pg_get_constraintdef(con.oid) || ';' AS line
  FROM pg_constraint con
  JOIN rel r ON r.oid = con.conrelid
  WHERE con.contype IN ('p', 'u', 'c', 'f')
),

-- 4. Indexes ---------------------------------------------------------------
-- Excluding the ones Postgres created to back a constraint above, which would
-- otherwise be created twice under a different name.
idx AS (
  SELECT 400 AS sect, i.indexrelid::regclass::text AS ord1, '' AS ord2,
         pg_get_indexdef(i.indexrelid) || ';' AS line
  FROM pg_index i
  JOIN rel r ON r.oid = i.indrelid
  WHERE NOT EXISTS (
    SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid
  )
),

-- 5. Views -----------------------------------------------------------------
vw AS (
  SELECT 500 AS sect, r.relname AS ord1, '' AS ord2,
         'CREATE OR REPLACE VIEW public.' || quote_ident(r.relname) ||
         ' AS' || E'\n' || pg_get_viewdef(r.oid, true) AS line
  FROM rel r
  WHERE r.relkind = 'v'
),

-- 6. Functions -------------------------------------------------------------
-- pg_get_functiondef gives the complete definition including SECURITY DEFINER
-- and any SET search_path, which is exactly what the security review needs.
fn AS (
  SELECT 600 AS sect, p.proname AS ord1, p.oid::text AS ord2,
         pg_get_functiondef(p.oid) || ';' AS line
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.prokind IN ('f', 'p')
    AND NOT EXISTS (
      SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e'
    )
),

-- 7. Triggers --------------------------------------------------------------
trg AS (
  SELECT 700 AS sect, t.tgname AS ord1, '' AS ord2,
         pg_get_triggerdef(t.oid) || ';' AS line
  FROM pg_trigger t
  JOIN rel r ON r.oid = t.tgrelid
  WHERE NOT t.tgisinternal
),

-- 8. Row Level Security ----------------------------------------------------
-- Emitted before the policies, since a policy on a table with RLS off is
-- inert and the ordering should make that impossible to get wrong.
rls AS (
  SELECT 800 AS sect, r.relname AS ord1, '' AS ord2,
         'ALTER TABLE public.' || quote_ident(r.relname) ||
         ' ENABLE ROW LEVEL SECURITY;' AS line
  FROM rel r
  WHERE r.relrowsecurity AND r.relkind IN ('r', 'p')
),

-- 9. Policies --------------------------------------------------------------
pol AS (
  SELECT 900 AS sect, p.tablename AS ord1, p.policyname AS ord2,
         'CREATE POLICY ' || quote_ident(p.policyname) ||
         ' ON public.' || quote_ident(p.tablename) ||
         CASE WHEN p.permissive = 'RESTRICTIVE' THEN ' AS RESTRICTIVE' ELSE '' END ||
         ' FOR ' || p.cmd ||
         ' TO ' || array_to_string(p.roles, ', ') ||
         COALESCE(' USING (' || p.qual || ')', '') ||
         COALESCE(' WITH CHECK (' || p.with_check || ')', '') || ';' AS line
  FROM pg_policies p
  WHERE p.schemaname = 'public'
),

-- 10. Table grants ---------------------------------------------------------
-- Aggregated per grantee so the output is one line per table per role rather
-- than one per privilege.
tgrant AS (
  SELECT 1000 AS sect, r.relname AS ord1, g.grantee AS ord2,
         'GRANT ' || string_agg(g.privilege_type, ', ' ORDER BY g.privilege_type) ||
         ' ON TABLE public.' || quote_ident(r.relname) ||
         ' TO ' || quote_ident(g.grantee) || ';' AS line
  FROM information_schema.role_table_grants g
  JOIN rel r ON r.relname = g.table_name
  WHERE g.table_schema = 'public'
    AND g.grantee NOT IN ('postgres', 'PUBLIC')
  GROUP BY r.relname, g.grantee
),

-- 11. Function privileges --------------------------------------------------
-- THE REASON THIS SECTION EXISTS
--
-- Postgres grants EXECUTE on every new function to PUBLIC by default, so the
-- interesting fact about a function is usually what has been taken AWAY.
-- 050_league_layer.sql revokes EXECUTE on bc_claim_league_seat from anon and
-- authenticated, because that function can flip a league invitation to
-- accepted and is SECURITY DEFINER. A baseline that loses that revoke gives
-- staging a hole production does not have.
--
-- So this emits an explicit REVOKE-then-GRANT for every function: revoke from
-- PUBLIC, then grant to exactly the roles that actually hold EXECUTE today.
fgrant AS (
  SELECT 1100 AS sect, p.proname AS ord1, p.oid::text AS ord2,
         'REVOKE ALL ON FUNCTION public.' || quote_ident(p.proname) ||
         '(' || pg_get_function_identity_arguments(p.oid) || ') FROM PUBLIC;' ||
         COALESCE(
           E'\n' || string_agg(
             'GRANT EXECUTE ON FUNCTION public.' || quote_ident(p.proname) ||
             '(' || pg_get_function_identity_arguments(p.oid) || ') TO ' ||
             quote_ident(role_name) || ';',
             E'\n' ORDER BY role_name),
           ''
         ) AS line
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  LEFT JOIN LATERAL (
    SELECT rolname AS role_name
    FROM pg_roles
    WHERE rolname IN ('anon', 'authenticated', 'service_role')
      AND has_function_privilege(rolname, p.oid, 'EXECUTE')
  ) g ON TRUE
  WHERE n.nspname = 'public'
    AND p.prokind IN ('f', 'p')
    AND NOT EXISTS (
      SELECT 1 FROM pg_depend d WHERE d.objid = p.oid AND d.deptype = 'e'
    )
  GROUP BY p.proname, p.oid
),

-- Section banners, so the downloaded file is readable by a person.
hdr AS (
  SELECT * FROM (VALUES
    (100,  '', '', '-- ===== EXTENSIONS ====='),
    (200,  '', '', '-- ===== TABLES ====='),
    (300,  '0', '', '-- ===== CONSTRAINTS ====='),
    (400,  '', '', '-- ===== INDEXES ====='),
    (500,  '', '', '-- ===== VIEWS ====='),
    (600,  '', '', '-- ===== FUNCTIONS ====='),
    (700,  '', '', '-- ===== TRIGGERS ====='),
    (800,  '', '', '-- ===== ROW LEVEL SECURITY ====='),
    (900,  '', '', '-- ===== POLICIES ====='),
    (1000, '', '', '-- ===== TABLE GRANTS ====='),
    (1100, '', '', '-- ===== FUNCTION PRIVILEGES =====')
  ) AS t(sect, ord1, ord2, line)
),

all_lines AS (
  SELECT * FROM pre
  UNION ALL SELECT * FROM hdr
  UNION ALL SELECT * FROM ext
  UNION ALL SELECT * FROM tbl
  UNION ALL SELECT * FROM cons
  UNION ALL SELECT * FROM idx
  UNION ALL SELECT * FROM vw
  UNION ALL SELECT * FROM fn
  UNION ALL SELECT * FROM trg
  UNION ALL SELECT * FROM rls
  UNION ALL SELECT * FROM pol
  UNION ALL SELECT * FROM tgrant
  UNION ALL SELECT * FROM fgrant
)

SELECT
  row_number() OVER (ORDER BY sect, ord1, ord2) AS n,
  line AS ddl
FROM all_lines
ORDER BY sect, ord1, ord2;
