// Emit the media backfill as SQL, from the same function the tests cover.
//
// scripts/backfill-drill-media.ts needs the service role key. Where that key is
// not available to the operator — and it should not be pasted anywhere — this
// produces the identical rows as INSERT statements to run through a trusted SQL
// console instead.
//
// The point is that mediaRowFor() is the single source. scripts/test-drill-media.ts
// asserts its preservation rules against all 208 real rows; hand-written SQL
// would be a second implementation with nothing asserting it matches the first.
//
//   npx tsx scripts/emit-media-backfill.ts > /tmp/backfill.sql

import { mediaRowFor } from './backfill-drill-media'
import { readFileSync } from 'fs'

const LIBRARY: any[] = JSON.parse(readFileSync('scripts/fixtures/drill-library-snapshot.json', 'utf8'))
const q = (v: any) => v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`
const n = (v: any) => v === null || v === undefined ? 'NULL' : String(Number(v))

const rows = LIBRARY.map(mediaRowFor).filter(Boolean) as any[]

console.log('-- Generated by scripts/emit-media-backfill.ts from mediaRowFor().')
console.log(`-- ${rows.length} rows. ON CONFLICT DO NOTHING against the unique`)
console.log('-- attachment index, so re-running is a no-op rather than a duplicate.')
console.log('INSERT INTO drill_media_resources')
console.log('  (drill_id, media_type, provider, external_id, url, title, source_name,')
console.log('   thumbnail_url, start_seconds, end_seconds, start_source, is_primary,')
console.log('   verification_status, notes)')
console.log('VALUES')
console.log(rows.map(r => `(${[
  q(r.drill_id), q(r.media_type), q(r.provider), q(r.external_id), q(r.url),
  q(r.title), q(r.source_name), q(r.thumbnail_url),
  n(r.start_seconds), n(r.end_seconds), q(r.start_source),
  r.is_primary ? 'true' : 'false', q(r.verification_status), q(r.notes),
].join(',')})`).join(',\n'))
console.log('ON CONFLICT DO NOTHING;')
