#!/usr/bin/env node
// Put the drill library into a staging database, and nothing else.
//
//   npm run staging:seed -- --check    # what is there now; writes nothing
//   npm run staging:seed               # seed it
//
// WHAT GETS SEEDED, AND WHY ONLY THIS
//
// Three tables: problem_taxonomy (49), drill_resources (206),
// drill_problem_map (348). They are reference data — a shared library of
// public YouTube drills and the coaching problems they address. No coach
// wrote them, no team owns them, and nothing in them is about a child.
//
// Nothing else is seeded. No coaches, no teams, no players, no notes, no
// scouting entries, no games. The instinct on a new staging database is to
// copy production so it "looks real", and it is the wrong instinct: those rows
// are the private records of real families, and a staging environment is by
// definition the one with looser access, fewer eyes on it, and credentials
// pasted into more places. A staging database with real player notes in it is
// a breach waiting for a misconfigured RLS policy.
//
// League E2E testing does not need them either. A league, a commissioner, a
// division and an invited coach are all created THROUGH THE PRODUCT — that is
// the flow being tested. Seeding them would test the seeding.
//
// WHERE THE DATA COMES FROM
//
// pilot/reference/*.json, a read-only export taken from production for the
// Instagram calibration pilot. Re-export with `npm run pilot:export`.
//
// THIS SCRIPT WILL NOT WRITE TO PRODUCTION
//
// Not even with BENCHCOACH_ALLOW_PRODUCTION_WRITE. Seeding is upserting 600
// rows over the live drill library, and there is no version of that anyone
// should be one typo away from. Changing production drill data is what the
// migrations are for.

import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { serviceClient } from './lib/env-guard.mjs'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')

// neverProduction, so the refusal does not offer an override this script would
// then ignore. --check only counts rows, and counting rows in production is
// both harmless and occasionally the thing you wanted, so it is not blocked.
const { db } = await serviceClient({
  script: `seed-staging${CHECK ? ' --check' : ''}`,
  writes: !CHECK,
  what: 'upserts the drill library into problem_taxonomy, drill_resources and drill_problem_map',
  neverProduction: true,
})

// ---------------------------------------------------------------------------

function load(name) {
  const doc = JSON.parse(readFileSync(resolve(ROOT, `pilot/reference/${name}.json`), 'utf8'))
  const rows = Array.isArray(doc) ? doc : doc.rows
  if (!Array.isArray(rows) || !rows.length) throw new Error(`pilot/reference/${name}.json has no rows`)
  return rows
}

/**
 * Refuse to seed anything that looks like a person.
 *
 * The export is reference data today. It is regenerated by a script, from a
 * live database, by whoever runs it next — so "it was clean when I looked" is
 * not a property the seed can rely on. This checks every time.
 */
function assertImpersonal(name, rows) {
  const PERSONAL = /(^|_)(coach|user|player|team|owner)_id$|email|phone|parent|guardian/i
  const offenders = new Map()
  for (const row of rows) {
    for (const [col, val] of Object.entries(row)) {
      if (!PERSONAL.test(col)) continue
      if (val === null || val === undefined || val === '') continue
      offenders.set(col, (offenders.get(col) || 0) + 1)
    }
  }
  if (offenders.size) {
    console.error(`\nREFUSING. ${name}.json carries data that identifies people:`)
    for (const [col, n] of offenders) console.error(`  ${col}: ${n} of ${rows.length} rows are populated`)
    console.error('\nStaging gets reference data only. Re-export, or strip these columns first.\n')
    process.exit(1)
  }
}

const taxonomy = load('problem_taxonomy')
const drills = load('drills')
const mappings = load('drill_problem_map')

for (const [name, rows] of [['problem_taxonomy', taxonomy], ['drills', drills], ['drill_problem_map', mappings]]) {
  assertImpersonal(name, rows)
}
console.log(`  reference data: ${taxonomy.length} problems, ${drills.length} drills, ${mappings.length} mappings`)
console.log('  checked for personal columns: none populated\n')

// ---------------------------------------------------------------------------

async function count(table) {
  const { count: n, error } = await db.from(table).select('*', { count: 'exact', head: true })
  if (error) return { n: null, error: error.message }
  return { n }
}

console.log('  currently in this database:')
for (const t of ['problem_taxonomy', 'drill_resources', 'drill_problem_map']) {
  const { n, error } = await count(t)
  console.log(`    ${t.padEnd(20)} ${n === null ? `unreadable — ${error}` : `${n} rows`}`)
}
console.log('')

if (CHECK) {
  console.log('  --check: nothing was written.\n')
  process.exit(0)
}

// ---------------------------------------------------------------------------
// Order matters: drill_problem_map references both of the others, so it goes
// last. Chunked because PostgREST will not take 348 rows and 38 columns in one
// request without timing out on a cold project.
// ---------------------------------------------------------------------------

async function upsert(table, rows, onConflict, chunk = 100) {
  let done = 0
  for (let i = 0; i < rows.length; i += chunk) {
    const slice = rows.slice(i, i + chunk)
    const { error } = await db.from(table).upsert(slice, { onConflict })
    if (error) throw new Error(`${table} rows ${i}-${i + slice.length}: ${error.message}`)
    done += slice.length
    process.stdout.write(`\r    ${table.padEnd(20)} ${done}/${rows.length}`)
  }
  process.stdout.write(`\r    ${table.padEnd(20)} ${done}/${rows.length} ✓\n`)
}

console.log('  seeding:')
await upsert('problem_taxonomy', taxonomy, 'slug')
await upsert('drill_resources', drills, 'id')
await upsert('drill_problem_map', mappings, 'drill_id,problem_slug')

console.log('\n  after:')
for (const t of ['problem_taxonomy', 'drill_resources', 'drill_problem_map']) {
  const { n, error } = await count(t)
  console.log(`    ${t.padEnd(20)} ${n === null ? `unreadable — ${error}` : `${n} rows`}`)
}

console.log('')
console.log('  Reference data only. No coach, team, player or game rows were created —')
console.log('  those are made through the product, which is the flow being tested.')
console.log('')
